### ISSUE TITLE
Disable secure connection(STARTTLS)

### ISSUE THREAD

**Issue by DeamonMV** [KeepSec-Technologies/Mail2Go#2]
Hello

Could you help to understand how to run `mail2go` without using secure connection?

What is my use case - I'm need to send test email for portForwarded postfix, which have  STARTTLS option, so the connection can be secured, but as long I'm doing test locally with portForwarding I don't need to have secure connection.

Thank you

**Comment by JCoupalK** [comment]
Hi, normally if there's no secure connection it should automatically detects it and make it work accordingly. What is the output it gives you when you try that if it doesn't work?

**Comment by DeamonMV** [comment]
Output of the command

```
Error sending email: dial failed: tls: failed to verify certificate: x509: certificate is valid for *.my.maindomain.com, my.maindomain.com, not localhost
```

**Comment by JCoupalK** [comment]
Oh ok I see, I can make a new release soon with more configuration options around TLS and TLS verification

**Comment by JCoupalK** [comment]
Hi, 

I made a new release (1.1.4). 

I tried a similar setup as yours locally and seems to work for me now using the new TLS option.

Can you try the new version and tell me how it goes?

The instructions are in the release description or the new README.

In your case you would be using "-l tls-skip"

**Comment by DeamonMV** [comment]
Hello.

I have tried new release.

But, I guess, right now I can't check it. I faced this "problem"

```
$ mail2go -h
mail2go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mail2go)
mail2go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mail2go)
```

My ENV

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
libc-bin:
  Installed: 2.31-13+deb11u5
  Candidate: 2.31-13+deb11u10
  Version table:
     2.31-13+deb11u10 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
     2.31-13+deb11u8 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
 *** 2.31-13+deb11u5 500
        500 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
libc6:
  Installed: 2.31-13+deb11u10
  Candidate: 2.31-13+deb11u10
  Version table:
 *** 2.31-13+deb11u10 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.31-13+deb11u8 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
     2.31-13+deb11u5 500
        500 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
```

Is it possible to build `mail2go` with older version of `glibc`?

**Comment by DeamonMV** [comment]
Anyway, I was to harsh, so I build one, for my self, from the source code, this solve this issue.

It's seems you set `-l` flag as [required ](https://github.com/KeepSec-Technologies/Mail2Go/commit/db4ce4b05023f11090f5865502758aa03408d480#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R162) and without default value.

I would say, that is not a good idea, because of if someone using your script for some automatic test, it will stop working. In general this release will give people bit of a pain to actual the command/scripts.

It's better to save the previous behavior, by setting corresponding default value.

My test show this option `-l` working. 

[Can you say what is difference](https://github.com/KeepSec-Technologies/Mail2Go/commit/db4ce4b05023f11090f5865502758aa03408d480#diff-daa9ecfaab79223ed86eeb0c3371062bd9dda447c0d969c85b68373dd67ebd79R54) in `tls-skip` and `none`  - for it acts identically .


BTW - it's possible to ask `mail2go` to print the email which will be send to the postfix? For debug purpose, to understand on my side(sender) what will get postfix?

Thank you for the quick release))

**Comment by JCoupalK** [comment]
Oh ok that might be because I built it with CGO enabled, I replaced the executables from the release tab with new ones built without CGO like before which should work. Try it and tell me how it goes

**Comment by JCoupalK** [comment]
Didn't saw your previous comment, glad it works now! 

The difference is none is no TLS certificate. tls-skip assumes the server has one but it will not verify if it's a valid one. 

As for the -l setting yeah I could put tls as a default now that I think about it, that's somewhat how it was before. I won't make a new release for it I'll replace the 1.1.4 executables.

As for the last question it's not possible currently, maybe in a future release but it sends either your body from the cli which can be tricky for a complicated message or an HTML file for assurance and if it's an HTML file it's gonna be the same at everytime.

**Comment by DeamonMV** [comment]
> Oh ok that might be because I built it with CGO enabled, I replaced the executables from the release tab with new ones built without CGO like before which should work. Try it and tell me how it goes

Now binary don't show any warnings

>As for the -l setting yeah I could put tls as a default now that I think about it, that's somewhat how it was before. I won't make a new release for it I'll replace the 1.1.4 executables.

I'll check it later.

Thanks

**Comment by JCoupalK** [comment]
> 
> Now binary don't show any warnings
> 
Perfect thank you for checking.

Also just uploaded the version without required -l option.
