### ISSUE TITLE
server does not support SMTP AUTH type: PLAIN

### ISSUE THREAD

**Issue by areqq** [KeepSec-Technologies/Mail2Go#3]
mail2go  -s smtp.office365.com -p 587 -l tls  -u smtpout@xxx.xx -w xxxxxxx -f xxx@xxxx -t xxxx@xxxx.xx -h 'Test Mail2Go Subject' -b 'This is a body!'

Error sending email: dial failed: server does not support SMTP AUTH type: PLAIN

can I use other AUTH type ?

**Comment by JCoupalK** [comment]
Hi,

Not at the moment but I could definitely add that in a future release.

I see that it's Office so it's gonna be the LOGIN auth type.

**Comment by JCoupalK** [comment]
Hi @areqq,

I made a new release that should resolve your issue.

I made the decision to just use LOGIN Auth instead of PLAIN since the majority of SMTP servers supports it by default anyway.

https://github.com/KeepSec-Technologies/Mail2Go/releases/tag/1.1.5
